json
"1FFxkVijzvUPUeHgkFjBk2Qw8j3wQY2cDw" : {
    "name" : "Foundry USA",
    "link" : "https://foundrydigital.com/"
},
"12KKDt4Mj7N5UAkQMN7LtPZMayenXHa8KL" : {
    "name" : "Foundry USA",
    "link" : "https://foundrydigital.com/"
},
